language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  # TODO: make 3.7-dev work
  # - "3.7-dev"
install:
  - sudo apt install -y coreutils
  - virtualenv env --python=python3
  - source env/bin/activate
  - pip install -r requirements.txt
  - pip install pylint
  - pip install codecov
  # Python3 needs root and setuid to allow test_kernel to add routes to the kernel
  - sudo chown root env/bin/python3
  - sudo chmod u+s env/bin/python3
  # Insert list of interfaces and their addresses in log
  - ifconfig
script:
  # We are strict; if the pylint score is not perfect, we fail the build
  # - pytest --cov=rift tests && \
  #   echo "Lint rift" && pylint rift && \
  #   echo "Lint tests" && pylint tests && \
  #   echo "Lint tools" && pylint tools && \
  #   tools/update_cli_docs.py -c
  # TODO: Get this to work
  - sudo tools/chaos-test-suite --new-venv --iterations 5
  
after_success:
  - codecov

after_failure:
  - tail -1000 rift_expect.log
  - tail -1000 rift_telnet_expect.log
  - tail -1000 test_telnet_expect.log
