language: python

os: linux

jobs:
  include:
  - dist: xenial
    python: 3.5
  - dist: xenial
    python: 3.6
  - dist: xenial
    python: 3.7
  - dist: xenial
    python: 3.8
  - dist: trusty
    python: 3.8
  - dist: focal
    python: 3.8

install:
  - virtualenv env --python=python3
  - source env/bin/activate
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.5" ]; then pip install -r requirements-3-567.txt; fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then pip install -r requirements-3-567.txt; fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ]; then pip install -r requirements-3-567.txt; fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then pip install -r requirements-3-8.txt; fi
  - pip install pylint
  - pip install codecov
  # Python3 needs root and setuid to allow test_kernel to add routes to the kernel
  - sudo chown root env/bin/python3
  - sudo chmod u+s env/bin/python3
  # Insert list of interfaces and their addresses in log
  - ifconfig

script:
  - pytest --cov=rift tests || tools/summarize-test-errors.sh
# Temporarily comment out while I get build matrixes to work correctly
#  - echo "lint rift" && pylint rift
#  - echo "lint tests" && pylint tests
#  - echo "lint tools" && pylint tools
#  - echo "check cli docs" && tools/update_cli_docs.py -c
#  - sudo tools/chaos-test-suite --new-venv --iterations 3 && tools/interface_stats.py
  
after_success:
  - codecov
