language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install codecov
script:
  # We are strict; if the pylint score is not perfect, we fail the build
  # Needs "sudo" for adding routes to the kernel route table (test_kernel)
  - sudo env/bin/pytest --cov=rift tests && pylint rift && pylint tests
  
after_success:
  - codecov
